/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-11-03 07:10:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.seat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class extendseat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/LG/Desktop/zajinmori/project/cafeSeatProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CafeSeatProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1729240665271L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<!--\r\n");
      out.write("	Astral by HTML5 UP\r\n");
      out.write("	html5up.net | @ajlkn\r\n");
      out.write("	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<title>Astral by HTML5 UP</title>\r\n");
      out.write("		<meta charset=\"utf-8\" />\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"/cafe/assets/css/main.css\" />\r\n");
      out.write("		<noscript><link rel=\"stylesheet\" href=\"/cafe/assets/css/noscript.css\" /></noscript>\r\n");
      out.write("\r\n");
      out.write("		<style>\r\n");
      out.write("			.seat {}\r\n");
      out.write("			.seat form {width:90%; margin:0 auto; display: flex; flex-wrap: wrap; border: 2px solid cornflowerblue; padding: 10px; box-sizing: Border-box; border-radius: 15px;}\r\n");
      out.write("			.seat form input {width: 13.7142%; padding: 15px; margin-right: 1%; display: inline-block;background-color: rgb(221, 221, 221); color: #444; font-weight: bold; color: #999;}\r\n");
      out.write("			.seat form input {margin-bottom: 10px; border-radius: 5px; box-shadow: 1px 1px 2px rgba(0,0,0,0.15);} \r\n");
      out.write("			.seat form input :nth-of-type(5n) {margin-right: 0;}\r\n");
      out.write("			.seat form input:hover {background: #aaa; color: #444;}\r\n");
      out.write("		\r\n");
      out.write("			.seat form input.booked {cursor:not-allowed; background-color: #666; pointer-events: none;}\r\n");
      out.write("			.seat form input.booked:hover {color: #999;}\r\n");
      out.write("			.seat form input.blank {margin-right: 13.7142%;}\r\n");
      out.write("			.seat form input:nth-child() {margin-bottom: 30px;}\r\n");
      out.write("			.seat form input.plug {background: url(/cafe/images/plug.png) no-repeat; background-size: 40%; background-position-x: right; background-position-y: bottom;}\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("			.bottom {width: 90%; margin: 20px auto; margin-top: 50px; display: flex; justify-content: space-between; border-top: 1px solid cornflowerblue; padding-top: 25px;}\r\n");
      out.write("\r\n");
      out.write("			.bottom #selectMenu {width: 30%;}\r\n");
      out.write("			.bottom #person {width: 20%;}\r\n");
      out.write("\r\n");
      out.write("			.storename{\r\n");
      out.write("				font-size: 200%; font-weight: bold; text-align: center; \r\n");
      out.write("			}\r\n");
      out.write("			.storeinfo{\r\n");
      out.write("				padding-top: 10%;\r\n");
      out.write("			}\r\n");
      out.write("			@font-face {\r\n");
      out.write("				font-family: 'Paperlogy-8ExtraBold';\r\n");
      out.write("				src: url('https://fastly.jsdelivr.net/gh/projectnoonnu/2408-3@1.0/Paperlogy-8ExtraBold.woff2') format('woff2');\r\n");
      out.write("				font-weight: 800;\r\n");
      out.write("				font-style: normal;\r\n");
      out.write("			}\r\n");
      out.write("			body{\r\n");
      out.write("				font-family: 'Paperlogy-8ExtraBold';\r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</style>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body class=\"is-preload\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Wrapper-->\r\n");
      out.write("			<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Nav -->\r\n");
      out.write("					<nav id=\"nav\">\r\n");
      out.write("						<a href=\"#\" class=\"icon solid fa-home\"><span>Home</span></a>\r\n");
      out.write("						<a href=\"#work\" class=\"icon solid fa-folder\"><span>Work</span></a>\r\n");
      out.write("						<a href=\"#contact\" class=\"icon solid fa-envelope\"><span>Contact</span></a>\r\n");
      out.write("						<a href=\"#Twitter\" class=\"icon brands fa-twitter\"><span>Twitter</span></a>\r\n");
      out.write("					</nav>\r\n");
      out.write("\r\n");
      out.write("				<!-- Main -->\r\n");
      out.write("					<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("						<!-- Me -->\r\n");
      out.write("							<article id=\"home\" class=\"panel intro\">\r\n");
      out.write("								<!-- <header>\r\n");
      out.write("									<h1>Jane Doe</h1>\r\n");
      out.write("									<p>Senior Astral Projectionist</p>\r\n");
      out.write("								</header>\r\n");
      out.write("								<a href=\"#work\" class=\"jumplink pic\">\r\n");
      out.write("									<span class=\"arrow icon solid fa-chevron-right\"><span>See my work</span></span>\r\n");
      out.write("									<img src=\"images/me.jpg\" alt=\"\" />\r\n");
      out.write("								</a> -->\r\n");
      out.write("							</article>\r\n");
      out.write("\r\n");
      out.write("						<!-- Work -->\r\n");
      out.write("							<article id=\"work\" class=\"panel\">\r\n");
      out.write("								\r\n");
      out.write("									<!-- 상단부 -->\r\n");
      out.write("								<h1 class=\"storename\">투썸플레이스 역삼성흥타워점</h1>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"storeinfo\">\r\n");
      out.write("									<p>\r\n");
      out.write("										서울 강남구 테헤란로 138 1층 투썸플레이스<br>\r\n");
      out.write("\r\n");
      out.write("											지번 | 역삼동 736<br>\r\n");
      out.write("\r\n");
      out.write("											영업 중<br>\r\n");
      out.write("											영업시간\r\n");
      out.write("											월~금 07:00 ~ 22:00\r\n");
      out.write("											토,일 08:00 ~ 22:00<br>\r\n");
      out.write("\r\n");
      out.write("											02-508-2388\r\n");
      out.write("\r\n");
      out.write("									</p>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("										<!-- 좌석 선택 -->\r\n");
      out.write("								<div class=\"seat\"> \r\n");
      out.write("									<form id=\"seatForm\" method=\"post\" action=\"\">\r\n");
      out.write("										<input type=\"button\" value=\"1\" class=\"booked seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"2\" class=\"plug seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"3\" class=\"blank seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"4\" class=\"blank plug seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"5\" class=\"plug seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"6\" class=\"seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"7\" class=\"seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"8\" class=\"blank seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"9\" class=\"blank seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"10\" class=\"seatButton\">\r\n");
      out.write("\r\n");
      out.write("										<hr style=\"width:100%; border:0;\" >\r\n");
      out.write("										<input type=\"button\" value=\"11\" class=\"seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"12\" class=\"blank seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"13\" class=\"seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"14\" class=\"blank seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"15\" class=\"seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"16\" class=\"plug seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"17\" class=\"blank seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"18\" class=\"plug seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"19\" class=\"blank seatButton\">\r\n");
      out.write("										<input type=\"button\" value=\"20\" class=\"plug seatButton\">\r\n");
      out.write("									\r\n");
      out.write("											<!-- 하단부 -->\r\n");
      out.write("										<div class=\"bottom\">\r\n");
      out.write("											<input type=\"number\" name=\"count\" id=\"person\" min=\"1\" max=\"4\" placeholder=\"인원 수\">\r\n");
      out.write("											<input type=\"submit\" value=\"메뉴선택\" id=\"selectMenu\">\r\n");
      out.write("										</div>\r\n");
      out.write("									</form>\r\n");
      out.write("									</div>\r\n");
      out.write("								\r\n");
      out.write("							</article>\r\n");
      out.write("\r\n");
      out.write("						<!-- Contact -->\r\n");
      out.write("							<article id=\"contact\" class=\"panel\">\r\n");
      out.write("								<!-- <header>\r\n");
      out.write("									<h2>Contact Me</h2>\r\n");
      out.write("								</header>\r\n");
      out.write("								<form action=\"#\" method=\"post\">\r\n");
      out.write("									<div>\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col-6 col-12-medium\">\r\n");
      out.write("												<input type=\"text\" name=\"name\" placeholder=\"Name\" />\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-6 col-12-medium\">\r\n");
      out.write("												<input type=\"text\" name=\"email\" placeholder=\"Email\" />\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-12\">\r\n");
      out.write("												<input type=\"text\" name=\"subject\" placeholder=\"Subject\" />\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-12\">\r\n");
      out.write("												<textarea name=\"message\" placeholder=\"Message\" rows=\"6\"></textarea>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-12\">\r\n");
      out.write("												<input type=\"submit\" value=\"Send Message\" />\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</form> -->\r\n");
      out.write("							</article>\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("							<!-- Twitter -->\r\n");
      out.write("							<article id=\"Twitter\" class=\"panel\">\r\n");
      out.write("							</article>					\r\n");
      out.write("							</div>\r\n");
      out.write("					\r\n");
      out.write("\r\n");
      out.write("				<!-- Footer -->\r\n");
      out.write("					<div id=\"footer\">\r\n");
      out.write("						<ul class=\"copyright\">\r\n");
      out.write("							<li>&copy; Untitled.</li><li>Design: <a href=\"http://html5up.net\">HTML5 UP</a></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Scripts -->\r\n");
      out.write("			<script src=\"/cafe/assets/js/jquery.min.js\"></script>\r\n");
      out.write("			<script src=\"/cafe/assets/js/browser.min.js\"></script>\r\n");
      out.write("			<script src=\"/cafe/assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("			<script src=\"/cafe/assets/js/util.js\"></script>\r\n");
      out.write("			<script src=\"/cafe/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("			<script>\r\n");
      out.write("					$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("						let selectedSeats = []; //좌석을 여러개 선택할 경우를 위해 배열로\r\n");
      out.write("						\r\n");
      out.write("					$('.seatButton').click(function() {\r\n");
      out.write("						const seatValue = $(this).val();\r\n");
      out.write("						const currentColor = $(this).css('background-color'); //원래 색\r\n");
      out.write("						const shadow = $(this).css('box-shadow'); //원래그림자\r\n");
      out.write("						const selectColor = 'rgb(255, 200, 100)'; // 선택했을때 색\r\n");
      out.write("						const selected = '5px 5px 10px -5px inset'; // 선택했을때 그림자\r\n");
      out.write("						alert(\"선택한 좌석:\" + seatValue);\r\n");
      out.write("\r\n");
      out.write("						if (selectedSeats.includes(seatValue)) {\r\n");
      out.write("							selectedSeats = selectedSeats.filter(seat => seat !== seatValue); //배열에 추가할지 안할지 걸러주는 필터역할~\r\n");
      out.write("							$(this).css('background-color', ''); // 원래 배경색으로 돌아감\r\n");
      out.write("							$(this).css('box-shadow',''); //원래 그림자로 돌아감\r\n");
      out.write("						} else {\r\n");
      out.write("							selectedSeats.push(seatValue);\r\n");
      out.write("							$(this).css('background-color', selectColor); // 선택시 배경색 변경\r\n");
      out.write("							$(this).css('box-shadow', selected); // 선택시 그림자 변경\r\n");
      out.write("							\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("				$('#seatForm').submit(function(event){\r\n");
      out.write("				if (selectedSeats.length > 0) {\r\n");
      out.write("					$.ajax({\r\n");
      out.write("						url: '서버url', // 실제 서버 URL로 변경해야함\r\n");
      out.write("						type: 'POST',\r\n");
      out.write("						data: {\r\n");
      out.write("							seats: selectedSeats,\r\n");
      out.write("							count: $('#person').val()\r\n");
      out.write("						},\r\n");
      out.write("						success: function(response) {\r\n");
      out.write("							alert('전송완료: ' + response);\r\n");
      out.write("							\r\n");
      out.write("						},\r\n");
      out.write("						error: function(jqXhr, textStatus, errorThrown) {\r\n");
      out.write("							alert('전송오류: ' + textStatus);\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("				} else {\r\n");
      out.write("					alert('좌석을 선택해주세요.');\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			</script>\r\n");
      out.write("\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
