/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-12-19 05:29:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/inc/footer.jsp", Long.valueOf(1733983260711L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1729240665271L));
    _jspx_dependants.put("/WEB-INF/views/inc/nav.jsp", Long.valueOf(1733918060466L));
    _jspx_dependants.put("jar:file:/C:/Users/LG/Desktop/zajinmori/project/JSPServletProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CafeSeatProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<!--\r\n");
      out.write("	Astral by HTML5 UP\r\n");
      out.write("	html5up.net | @ajlkn\r\n");
      out.write("	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>CafeSeat</title>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../assets/css/main.css\" />\r\n");
      out.write("<noscript>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"../assets/css/noscript.css\" />\r\n");
      out.write("</noscript>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("@import url(\"/cafe/assets/css/paperlogy_font.css\");\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'Paperlogy-8ExtraBold';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mypage h1 {\r\n");
      out.write("	border: 5px solid #AF8F6F;\r\n");
      out.write("	background-color: #AF8F6F;\r\n");
      out.write("	padding: 25px;\r\n");
      out.write("	margin-bottom: 40px;\r\n");
      out.write("	margin-left: 80px;\r\n");
      out.write("	margin-right: 80px;\r\n");
      out.write("	margin-top: 0;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: #F8F4E1;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	font-family: 'Paperlogy-6SemiBold';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mypage div {\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-family: 'Paperlogy-5Medium';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mypage div input {\r\n");
      out.write("	margin: 0 50px 50px 50px;\r\n");
      out.write("	border: 3px solid #AF8F6F;\r\n");
      out.write("	background-color: #AF8F6F;\r\n");
      out.write("	color: #F8F4E1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mypage div input:hover {\r\n");
      out.write("	border: 3px solid #AF8F6F;\r\n");
      out.write("	background-color: #F8F4E1;\r\n");
      out.write("	color: #AF8F6F;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content-box {\r\n");
      out.write("	border: 3px solid #543310;\r\n");
      out.write("	padding: 40px;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	margin-left: 80px;\r\n");
      out.write("	margin-right: 80px;\r\n");
      out.write("	width: auto;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	background-color: #74512D;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mypage div .content-info {\r\n");
      out.write("	border: 5px solid #74512D;\r\n");
      out.write("	margin: 30px;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	font-family: 'Paperlogy-5Medium';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mypage div .content-info:hover {\r\n");
      out.write("	border: 5px solid##74512D;\r\n");
      out.write("	margin: 30px;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	background-color: #F8F4E1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mypage .content-info span:nth-child(1) {\r\n");
      out.write("	display: block;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	padding-left: 30px;\r\n");
      out.write("	margin-top: 40px;\r\n");
      out.write("	font-size: larger;\r\n");
      out.write("	color: #543310;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mypage .content-info span:nth-child(2) {\r\n");
      out.write("	display: block;\r\n");
      out.write("	text-align: right;\r\n");
      out.write("	padding-right: 30px;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	color: #AF8F6F;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mypage .content-info span:nth-child(3) {\r\n");
      out.write("	display: block;\r\n");
      out.write("	text-align: right;\r\n");
      out.write("	padding-right: 30px;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	color: #AF8F6F;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body class=\"is-preload\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Wrapper-->\r\n");
      out.write("	<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Nav -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav id=\"nav\"\r\n");
      out.write("	style=\"display: flex; align-items: center; justify-content: space-between;\">\r\n");
      out.write("	<div class=\"logo\" style=\"margin-right: 850px;\">\r\n");
      out.write("		<a href=\"/cafe/cafe/cafemap.do\" style=\"opacity: 1;\"> <img src=\"../images/Logo.png\"\r\n");
      out.write("			style=\"width: 350px; height: 100px;\" alt=\"Logo\">\r\n");
      out.write("		</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div style=\"flex: 1; display: flex; justify-content: center;\">\r\n");
      out.write("		<a href=\"/cafe/cafe/cafemap.do\" class=\"icon solid fa-map\"><span>Map</span></a>\r\n");
      out.write("		<!-- <a href=\"/cafe/seat/selectseat.do\" class=\"icon solid fa-mug-hot\"><span>CafeSeat</span></a>  -->\r\n");
      out.write("		<a href=\"/cafe/mypage/mypage.do\" class=\"icon solid fa-heart\"><span>MyPage</span></a>\r\n");
      out.write("\r\n");
      out.write("		<!-- 로그인 안 했을 때 -->\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- 로그인 했을 때  -->\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<!-- Main -->\r\n");
      out.write("		<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("<!-- 			<!-- map -- >\r\n");
      out.write("			<article id=\"home\" class=\"panel intro\"></article>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<article id=\"cafeseat\" class=\"panel\"></article>-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("			<article id=\"mypage\" class=\"panel\"> \r\n");
      out.write("				<h1>MYPAGE</h1>\r\n");
      out.write("				<div>\r\n");
      out.write("				    <input type=\"button\" class=\"btn btn-outline-primary btn-lg\" id=\"btn-reservation\" value=\"예약내역\">\r\n");
      out.write("				    <input type=\"button\" class=\"btn btn-outline-primary btn-lg\" id=\"btn-favorite\" value=\"즐겨찾기\">\r\n");
      out.write("				    <input type=\"button\" class=\"btn btn-outline-primary btn-lg\" id=\"btn-coupon\" value=\"쿠폰함\">\r\n");
      out.write("				    <input type=\"button\" class=\"btn btn-outline-primary btn-lg\" id=\"btn-myinfo\" value=\"내정보\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"content\"></div>\r\n");
      out.write("			</article>\r\n");
      out.write("<!-- \r\n");
      out.write("\r\n");
      out.write("			login\r\n");
      out.write("			<article id=\"login\" class=\"panel\"></article>\r\n");
      out.write("		</div>\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Footer -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("	<ul class=\"copyright\">\r\n");
      out.write("		<li>&copy; SIST-SideProject</li>\r\n");
      out.write("		<li>MEMBER : 김유진 김유리 이우진 장지윤 전상수</li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Scripts -->\r\n");
      out.write("	<script src=\"../assets/js/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"../assets/js/browser.min.js\"></script>\r\n");
      out.write("	<script src=\"../assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("	<script src=\"..//assets/js/util.js\"></script>\r\n");
      out.write("	<script src=\"../assets/js/main.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("	    var currentContent = '';\r\n");
      out.write("\r\n");
      out.write("	    function toggleContent(buttonId, content) {\r\n");
      out.write("	        if (currentContent === buttonId) {\r\n");
      out.write("	            $('#content').empty();\r\n");
      out.write("	            currentContent = '';\r\n");
      out.write("	        } else {\r\n");
      out.write("	            $('#content').empty().append(content);\r\n");
      out.write("	            currentContent = buttonId;\r\n");
      out.write("	        }\r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("	    $(\"#btn-favorite\").click(function() {\r\n");
      out.write("	        var favoriteContent = `\r\n");
      out.write("	            <div id=\"content-box\">\r\n");
      out.write("	                <div class=\"content-info\">\r\n");
      out.write("	                    <span>투썸플레이스 역삼성홍타워점</span>\r\n");
      out.write("	                    <span>남은좌석수: 20석</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div class=\"content-info\">\r\n");
      out.write("	                    <span>투썸플레이스 강남대륭타워점</span>\r\n");
      out.write("	                    <span>남은좌석수: 20석</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("	                <div class=\"content-info\">\r\n");
      out.write("	                    <span>스타벅스 강남R점</span>\r\n");
      out.write("	                    <span>남은좌석수: 20석</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        `;\r\n");
      out.write("	        toggleContent('favorite', favoriteContent);\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    $(\"#btn-reservation\").click(function() {\r\n");
      out.write("	        var reservationContent = `\r\n");
      out.write("	            <div id=\"content-box\">\r\n");
      out.write("	                <div class=\"content-info\">\r\n");
      out.write("	                    <span>투썸플레이스 역삼성홍타워점</span>\r\n");
      out.write("	                    <span>예약좌석: 00</span>\r\n");
      out.write("	                    <span>예약날짜: 2024-12-11</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        `;\r\n");
      out.write("	        toggleContent('reservation', reservationContent);\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    $(\"#btn-coupon\").click(function() {\r\n");
      out.write("	        var couponContent = `\r\n");
      out.write("	            <div id=\"content-box\">\r\n");
      out.write("	                <div class=\"content-info\">\r\n");
      out.write("	                    <span>아메리카노 1잔 무료</span>\r\n");
      out.write("	                    <span>유효기간: 2024-12-31</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        `;\r\n");
      out.write("	        toggleContent('coupon', couponContent);\r\n");
      out.write("	    });\r\n");
      out.write("\r\n");
      out.write("	    $(\"#btn-myinfo\").click(function() {\r\n");
      out.write("	        var myInfoContent = `\r\n");
      out.write("	            <div id=\"content-box\">\r\n");
      out.write("	                <div class=\"content-info\">\r\n");
      out.write("	                    <span>이름: 홍길동</span>\r\n");
      out.write("	                    <span>이메일: hong@example.com</span>\r\n");
      out.write("	                    <span>전화번호: 010-1234-5678</span>\r\n");
      out.write("	                </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        `;\r\n");
      out.write("	        toggleContent('myinfo', myInfoContent);\r\n");
      out.write("	    });\r\n");
      out.write("	});\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/inc/nav.jsp(18,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty auth}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<a href=\"/cafe/user/login.do\" class=\"icon solid fa-user\"><span>Login</span></a>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/inc/nav.jsp(23,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty auth}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<a href=\"/cafe/user/logout.do\" class=\"icon solid fa-user\"><span>Logout</span></a>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
