/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-12-19 05:27:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/inc/footer.jsp", Long.valueOf(1733983260711L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1729240665271L));
    _jspx_dependants.put("/WEB-INF/views/inc/nav.jsp", Long.valueOf(1733918060466L));
    _jspx_dependants.put("jar:file:/C:/Users/LG/Desktop/zajinmori/project/JSPServletProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/CafeSeatProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>CafeSeat</title>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/cafe/assets/css/main.css\" />\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"../assets/css/login.css\" />\r\n");
      out.write("	<noscript><link rel=\"stylesheet\" href=\"/cafe/assets/css/noscript.css\" /></noscript>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("@import url(\"/cafe/assets/css/paperlogy_font.css\");\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'Paperlogy-8ExtraBold';\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body class=\"is-preload\">\r\n");
      out.write("\r\n");
      out.write("	<!-- Wrapper-->\r\n");
      out.write("	<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("		<!-- Nav -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav id=\"nav\"\r\n");
      out.write("	style=\"display: flex; align-items: center; justify-content: space-between;\">\r\n");
      out.write("	<div class=\"logo\" style=\"margin-right: 850px;\">\r\n");
      out.write("		<a href=\"/cafe/cafe/cafemap.do\" style=\"opacity: 1;\"> <img src=\"../images/Logo.png\"\r\n");
      out.write("			style=\"width: 350px; height: 100px;\" alt=\"Logo\">\r\n");
      out.write("		</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div style=\"flex: 1; display: flex; justify-content: center;\">\r\n");
      out.write("		<a href=\"/cafe/cafe/cafemap.do\" class=\"icon solid fa-map\"><span>Map</span></a>\r\n");
      out.write("		<!-- <a href=\"/cafe/seat/selectseat.do\" class=\"icon solid fa-mug-hot\"><span>CafeSeat</span></a>  -->\r\n");
      out.write("		<a href=\"/cafe/mypage/mypage.do\" class=\"icon solid fa-heart\"><span>MyPage</span></a>\r\n");
      out.write("\r\n");
      out.write("		<!-- 로그인 안 했을 때 -->\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- 로그인 했을 때  -->\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Main -->\r\n");
      out.write("		<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("			<!-- Login -->\r\n");
      out.write("			<article id=\"login\" class=\"panel\">\r\n");
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</article>\r\n");
      out.write("\r\n");
      out.write("			<!-- Me -->\r\n");
      out.write("			<article id=\"home\" class=\"panel intro\"></article>\r\n");
      out.write("\r\n");
      out.write("			<!-- CafeSeat -->\r\n");
      out.write("			<article id=\"cafeseat\" class=\"panel\"></article>\r\n");
      out.write("\r\n");
      out.write("			<!-- Mypage -->\r\n");
      out.write("			<article id=\"mypage\" class=\"panel\"></article>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- Footer -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("	<ul class=\"copyright\">\r\n");
      out.write("		<li>&copy; SIST-SideProject</li>\r\n");
      out.write("		<li>MEMBER : 김유진 김유리 이우진 장지윤 전상수</li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- Scripts -->\r\n");
      out.write("	<script src=\"/cafe/assets/js/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"/cafe/assets/js/browser.min.js\"></script>\r\n");
      out.write("	<script src=\"/cafe/assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("	<script src=\"/cafe/assets/js/util.js\"></script>\r\n");
      out.write("	<script src=\"/cafe/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		document.querySelectorAll('input[name=\"opt-login\"]').forEach((radio) => {\r\n");
      out.write("		    radio.addEventListener('change', () => {\r\n");
      out.write("		        document.getElementById('loginType').value = radio.value; // 히든 필드에 라디오 버튼 값 설정\r\n");
      out.write("		    });\r\n");
      out.write("		});\r\n");
      out.write("   	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/inc/nav.jsp(18,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty auth}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<a href=\"/cafe/user/login.do\" class=\"icon solid fa-user\"><span>Login</span></a>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/inc/nav.jsp(23,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty auth}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<a href=\"/cafe/user/logout.do\" class=\"icon solid fa-user\"><span>Logout</span></a>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/user/login.jsp(37,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty auth}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<div class=\"banner\">\r\n");
          out.write("						<a href=\"/cafe/cafe/cafemap.do\" style=\"opacity: 1;\"> <img\r\n");
          out.write("							src=\"../images/Logo-Dark.png\" alt=\"Logo\">\r\n");
          out.write("						</a>\r\n");
          out.write("					</div>\r\n");
          out.write("					<div class=\"panel-content\">\r\n");
          out.write("						<div class=\"opt-login-form\">\r\n");
          out.write("							<input type=\"radio\" id=\"user\" class=\"opt-login\" name=\"opt-login\" value=\"user\" checked> \r\n");
          out.write("								<label for=\"user\" class=\"choice\">사용자 로그인</label> \r\n");
          out.write("							<input type=\"radio\" id=\"admin\" class=\"opt-login\" name=\"opt-login\" value=\"admin\"> \r\n");
          out.write("								<label for=\"admin\" class=\"choice\">관리자 로그인</label>\r\n");
          out.write("						</div>\r\n");
          out.write("\r\n");
          out.write("						<form method=\"post\" action=\"/cafe/user/login.do\">\r\n");
          out.write("							<div class=\"login-form\">\r\n");
          out.write("								<table class=\"login-table\">\r\n");
          out.write("									<tr>\r\n");
          out.write("										<th>아이디</th>\r\n");
          out.write("										<td><input type=\"text\" name=\"id\" id=\"id\"\r\n");
          out.write("											placeholder=\"영문, 숫자 조합 5~12자\" required></td>\r\n");
          out.write("									</tr>\r\n");
          out.write("									<tr>\r\n");
          out.write("										<th>비밀번호</th>\r\n");
          out.write("										<td><input type=\"password\" name=\"pw\" id=\"pw\"\r\n");
          out.write("											placeholder=\"영문, 숫자, 특수문자 3가지 조합 9~16자\" required></td>\r\n");
          out.write("									</tr>\r\n");
          out.write("								</table>\r\n");
          out.write("								<input type=\"hidden\" name=\"loginType\" id=\"loginType\" value=\"user\">\r\n");
          out.write("							</div>\r\n");
          out.write("\r\n");
          out.write("							<div class=\"login-button\">\r\n");
          out.write("								<button class=\"btnLogin\" type=\"submit\">로그인</button>\r\n");
          out.write("							</div>\r\n");
          out.write("						</form>\r\n");
          out.write("\r\n");
          out.write("						<!-- 빠른 로그인을 위한 원클릭 로그인 버튼: 테스트 후 삭제 예정 -->\r\n");
          out.write("						<div style=\"font-size: .8em;\">사용자 계정</div>\r\n");
          out.write("						<div style=\"display: flex;\">\r\n");
          out.write("							<form method=\"POST\" action=\"/cafe/user/login.do\">\r\n");
          out.write("								<input type=\"hidden\" name=\"id\" value=\"user\">\r\n");
          out.write("								<input type=\"hidden\" name=\"pw\" value=\"1111\">\r\n");
          out.write("								<input type=\"hidden\" name=\"loginType\" value=\"user\">\r\n");
          out.write("								<input type=\"submit\" value=\"사용자\">\r\n");
          out.write("							</form>\r\n");
          out.write("							<form method=\"POST\" action=\"/cafe/user/login.do\">\r\n");
          out.write("								<input type=\"hidden\" name=\"id\" value=\"yuri\">\r\n");
          out.write("								<input type=\"hidden\" name=\"pw\" value=\"1111\">\r\n");
          out.write("								<input type=\"hidden\" name=\"loginType\" value=\"user\">\r\n");
          out.write("								<input type=\"submit\" value=\"김유리\">\r\n");
          out.write("							</form>\r\n");
          out.write("							<form method=\"POST\" action=\"/cafe/user/login.do\">\r\n");
          out.write("								<input type=\"hidden\" name=\"id\" value=\"yujin\">\r\n");
          out.write("								<input type=\"hidden\" name=\"pw\" value=\"1111\">\r\n");
          out.write("								<input type=\"hidden\" name=\"loginType\" value=\"user\">\r\n");
          out.write("								<input type=\"submit\" value=\"김유진\">\r\n");
          out.write("							</form>\r\n");
          out.write("							<form method=\"POST\" action=\"/cafe/user/login.do\">\r\n");
          out.write("								<input type=\"hidden\" name=\"id\" value=\"woojin\">\r\n");
          out.write("								<input type=\"hidden\" name=\"pw\" value=\"1111\">\r\n");
          out.write("								<input type=\"hidden\" name=\"loginType\" value=\"user\">\r\n");
          out.write("								<input type=\"submit\" value=\"이우진\">\r\n");
          out.write("							</form>\r\n");
          out.write("							<form method=\"POST\" action=\"/cafe/user/login.do\">\r\n");
          out.write("								<input type=\"hidden\" name=\"id\" value=\"jiyun\">\r\n");
          out.write("								<input type=\"hidden\" name=\"pw\" value=\"1111\">\r\n");
          out.write("								<input type=\"hidden\" name=\"loginType\" value=\"user\">\r\n");
          out.write("								<input type=\"submit\" value=\"장지윤\">\r\n");
          out.write("							</form>\r\n");
          out.write("							<form method=\"POST\" action=\"/cafe/user/login.do\">\r\n");
          out.write("								<input type=\"hidden\" name=\"id\" value=\"sangsoo\">\r\n");
          out.write("								<input type=\"hidden\" name=\"pw\" value=\"1111\">\r\n");
          out.write("								<input type=\"hidden\" name=\"loginType\" value=\"user\">\r\n");
          out.write("								<input type=\"submit\" value=\"전상수\">\r\n");
          out.write("							</form>\r\n");
          out.write("						</div>\r\n");
          out.write("						<div style=\"font-size: .8em;\">관리자 계정</div>\r\n");
          out.write("						<div style=\"display: flex;\">\r\n");
          out.write("							<form method=\"POST\" action=\"/cafe/user/login.do\">\r\n");
          out.write("								<input type=\"hidden\" name=\"id\" value=\"admin\">\r\n");
          out.write("								<input type=\"hidden\" name=\"pw\" value=\"1111\">\r\n");
          out.write("								<input type=\"hidden\" name=\"loginType\" value=\"admin\">\r\n");
          out.write("								<input type=\"submit\" value=\"관리자\">\r\n");
          out.write("							</form>\r\n");
          out.write("							<form method=\"POST\" action=\"/cafe/user/login.do\">\r\n");
          out.write("								<input type=\"hidden\" name=\"id\" value=\"yuri\">\r\n");
          out.write("								<input type=\"hidden\" name=\"pw\" value=\"1111\">\r\n");
          out.write("								<input type=\"hidden\" name=\"loginType\" value=\"admin\">\r\n");
          out.write("								<input type=\"submit\" value=\"김유리\">\r\n");
          out.write("							</form>\r\n");
          out.write("							<form method=\"POST\" action=\"/cafe/user/login.do\">\r\n");
          out.write("								<input type=\"hidden\" name=\"id\" value=\"yujin\">\r\n");
          out.write("								<input type=\"hidden\" name=\"pw\" value=\"1111\">\r\n");
          out.write("								<input type=\"hidden\" name=\"loginType\" value=\"admin\">\r\n");
          out.write("								<input type=\"submit\" value=\"김유진\">\r\n");
          out.write("							</form>\r\n");
          out.write("							<form method=\"POST\" action=\"/cafe/user/login.do\">\r\n");
          out.write("								<input type=\"hidden\" name=\"id\" value=\"woojin\">\r\n");
          out.write("								<input type=\"hidden\" name=\"pw\" value=\"1111\">\r\n");
          out.write("								<input type=\"hidden\" name=\"loginType\" value=\"admin\">\r\n");
          out.write("								<input type=\"submit\" value=\"이우진\">\r\n");
          out.write("							</form>\r\n");
          out.write("							<form method=\"POST\" action=\"/cafe/user/login.do\">\r\n");
          out.write("								<input type=\"hidden\" name=\"id\" value=\"jiyun\">\r\n");
          out.write("								<input type=\"hidden\" name=\"pw\" value=\"1111\">\r\n");
          out.write("								<input type=\"hidden\" name=\"loginType\" value=\"admin\">\r\n");
          out.write("								<input type=\"submit\" value=\"장지윤\">\r\n");
          out.write("							</form>\r\n");
          out.write("							<form method=\"POST\" action=\"/cafe/user/login.do\">\r\n");
          out.write("								<input type=\"hidden\" name=\"id\" value=\"sangsoo\">\r\n");
          out.write("								<input type=\"hidden\" name=\"pw\" value=\"1111\">\r\n");
          out.write("								<input type=\"hidden\" name=\"loginType\" value=\"admin\">\r\n");
          out.write("								<input type=\"submit\" value=\"전상수\">\r\n");
          out.write("							</form>\r\n");
          out.write("						</div>\r\n");
          out.write("\r\n");
          out.write("						<div class=\"link\">\r\n");
          out.write("							<a href=\"#\" class=\"register\"\r\n");
          out.write("								onclick=\"alert('회원가입 페이지로 이동합니다!'); location.href='/cafe/user/register.do#login';\">회원가입</a>\r\n");
          out.write("							<a href=\"#\" class=\"findId\"\r\n");
          out.write("								onclick=\"alert('아이디 찾기 페이지로 이동합니다!'); location.href='/cafe/user/findId.do';\">아이디\r\n");
          out.write("								찾기</a> <a href=\"#\" class=\"findPw\"\r\n");
          out.write("								onclick=\"alert('비밀번호 찾기 페이지로 이동합니다!'); location.href='/cafe/user/findPw.do';\">비밀번호\r\n");
          out.write("								찾기</a>\r\n");
          out.write("						</div>\r\n");
          out.write("					</div>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
